version: '3'

services:

  api:
    build: .
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    stop_signal: SIGKILL
    environment:
      - DATABASE_URL=postgres://root:password@database:5432/bobotinho
      - REDIS_URL=redis://redis
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - net
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_DB=bobotinho
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    networks:
      - net

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
